import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Peony",
  description: "Generated by a rumeza :)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className="min-h-screen bg-cover bg-center bg-no-repeat bg-opacity-10"
       style={{ backgroundImage: "url('/bg.png')" }}
      >
        {children}
      </body>
    </html>
  );
}
